/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.DeviceRegistrationInfo;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeviceApi
 */
@Ignore
public class DeviceApiTest {

    private final DeviceApi api = new DeviceApi();

    
    /**
     * 
     *
     * returns all registered devices
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDevicesTest() throws Exception {
        Integer skip = null;
        Integer limit = null;
        List<String> response = api.getDevices(skip, limit);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void registerTest() throws Exception {
        DeviceRegistrationInfo device = null;
        api.register(device);

        // TODO: test validations
    }
    
}
