/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.DeviceState;
import io.swagger.client.model.LightingSummary;
import io.swagger.client.model.ModelApiResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ZWaveApi
 */
@Ignore
public class ZWaveApiTest {

    private final ZWaveApi api = new ZWaveApi();

    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getLightingSummaryTest() throws Exception {
        LightingSummary response = api.getLightingSummary();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSwitchStateTest() throws Exception {
        String deviceId = null;
        DeviceState response = api.getSwitchState(deviceId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void setDimmerTest() throws Exception {
        String deviceId = null;
        Integer value = null;
        ModelApiResponse response = api.setDimmer(deviceId, value);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * sets a dimmer to a specific value on a timer
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void setDimmerTimerTest() throws Exception {
        String deviceId = null;
        Integer value = null;
        Integer timeunit = null;
        String units = null;
        ModelApiResponse response = api.setDimmerTimer(deviceId, value, timeunit, units);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void setSwitchTest() throws Exception {
        String deviceId = null;
        String value = null;
        ModelApiResponse response = api.setSwitch(deviceId, value);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * sets a switch to a specific value on a timer
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void setSwitchTimerTest() throws Exception {
        String deviceId = null;
        String value = null;
        Integer minutes = null;
        ModelApiResponse response = api.setSwitchTimer(deviceId, value, minutes);

        // TODO: test validations
    }
    
}
