/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ForecastTemperature;
import io.swagger.client.model.WeatherForecast;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Forecast
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-12T15:25:46.864Z")
public class Forecast {
  @SerializedName("date")
  private OffsetDateTime date = null;

  @SerializedName("pressure")
  private Double pressure = null;

  @SerializedName("humidity")
  private Integer humidity = null;

  @SerializedName("windSpeed")
  private Double windSpeed = null;

  @SerializedName("clouds")
  private Integer clouds = null;

  @SerializedName("temperature")
  private ForecastTemperature temperature = null;

  @SerializedName("weather")
  private WeatherForecast weather = null;

  public Forecast date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public Forecast pressure(Double pressure) {
    this.pressure = pressure;
    return this;
  }

   /**
   * Get pressure
   * @return pressure
  **/
  @ApiModelProperty(value = "")
  public Double getPressure() {
    return pressure;
  }

  public void setPressure(Double pressure) {
    this.pressure = pressure;
  }

  public Forecast humidity(Integer humidity) {
    this.humidity = humidity;
    return this;
  }

   /**
   * Get humidity
   * @return humidity
  **/
  @ApiModelProperty(value = "")
  public Integer getHumidity() {
    return humidity;
  }

  public void setHumidity(Integer humidity) {
    this.humidity = humidity;
  }

  public Forecast windSpeed(Double windSpeed) {
    this.windSpeed = windSpeed;
    return this;
  }

   /**
   * Get windSpeed
   * @return windSpeed
  **/
  @ApiModelProperty(value = "")
  public Double getWindSpeed() {
    return windSpeed;
  }

  public void setWindSpeed(Double windSpeed) {
    this.windSpeed = windSpeed;
  }

  public Forecast clouds(Integer clouds) {
    this.clouds = clouds;
    return this;
  }

   /**
   * Get clouds
   * @return clouds
  **/
  @ApiModelProperty(value = "")
  public Integer getClouds() {
    return clouds;
  }

  public void setClouds(Integer clouds) {
    this.clouds = clouds;
  }

  public Forecast temperature(ForecastTemperature temperature) {
    this.temperature = temperature;
    return this;
  }

   /**
   * Get temperature
   * @return temperature
  **/
  @ApiModelProperty(value = "")
  public ForecastTemperature getTemperature() {
    return temperature;
  }

  public void setTemperature(ForecastTemperature temperature) {
    this.temperature = temperature;
  }

  public Forecast weather(WeatherForecast weather) {
    this.weather = weather;
    return this;
  }

   /**
   * Get weather
   * @return weather
  **/
  @ApiModelProperty(value = "")
  public WeatherForecast getWeather() {
    return weather;
  }

  public void setWeather(WeatherForecast weather) {
    this.weather = weather;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Forecast forecast = (Forecast) o;
    return Objects.equals(this.date, forecast.date) &&
        Objects.equals(this.pressure, forecast.pressure) &&
        Objects.equals(this.humidity, forecast.humidity) &&
        Objects.equals(this.windSpeed, forecast.windSpeed) &&
        Objects.equals(this.clouds, forecast.clouds) &&
        Objects.equals(this.temperature, forecast.temperature) &&
        Objects.equals(this.weather, forecast.weather);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, pressure, humidity, windSpeed, clouds, temperature, weather);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Forecast {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    pressure: ").append(toIndentedString(pressure)).append("\n");
    sb.append("    humidity: ").append(toIndentedString(humidity)).append("\n");
    sb.append("    windSpeed: ").append(toIndentedString(windSpeed)).append("\n");
    sb.append("    clouds: ").append(toIndentedString(clouds)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    weather: ").append(toIndentedString(weather)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

