/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LightingZone;
import io.swagger.client.model.LightingZoneStatus;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ok
 */
@ApiModel(description = "ok")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-12T15:25:46.864Z")
public class LightingSummary {
  @SerializedName("zones")
  private List<LightingZone> zones = null;

  @SerializedName("zoneStatus")
  private List<LightingZoneStatus> zoneStatus = null;

  public LightingSummary zones(List<LightingZone> zones) {
    this.zones = zones;
    return this;
  }

  public LightingSummary addZonesItem(LightingZone zonesItem) {
    if (this.zones == null) {
      this.zones = new ArrayList<LightingZone>();
    }
    this.zones.add(zonesItem);
    return this;
  }

   /**
   * Get zones
   * @return zones
  **/
  @ApiModelProperty(value = "")
  public List<LightingZone> getZones() {
    return zones;
  }

  public void setZones(List<LightingZone> zones) {
    this.zones = zones;
  }

  public LightingSummary zoneStatus(List<LightingZoneStatus> zoneStatus) {
    this.zoneStatus = zoneStatus;
    return this;
  }

  public LightingSummary addZoneStatusItem(LightingZoneStatus zoneStatusItem) {
    if (this.zoneStatus == null) {
      this.zoneStatus = new ArrayList<LightingZoneStatus>();
    }
    this.zoneStatus.add(zoneStatusItem);
    return this;
  }

   /**
   * Get zoneStatus
   * @return zoneStatus
  **/
  @ApiModelProperty(value = "")
  public List<LightingZoneStatus> getZoneStatus() {
    return zoneStatus;
  }

  public void setZoneStatus(List<LightingZoneStatus> zoneStatus) {
    this.zoneStatus = zoneStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LightingSummary lightingSummary = (LightingSummary) o;
    return Objects.equals(this.zones, lightingSummary.zones) &&
        Objects.equals(this.zoneStatus, lightingSummary.zoneStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(zones, zoneStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LightingSummary {\n");
    
    sb.append("    zones: ").append(toIndentedString(zones)).append("\n");
    sb.append("    zoneStatus: ").append(toIndentedString(zoneStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

